### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by iminochkin** [dhakehurst/net.akehurst.language#22]
net.akehurst.language with ./gradlew -v

------------------------------------------------------------
Gradle 6.3
------------------------------------------------------------

Build time:   2020-03-24 19:52:07 UTC
Revision:     bacd40b727b0130eeac8855ae3f9fd9a0b207c60

Kotlin:       1.3.70
Groovy:       2.5.10
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Mac OS X 10.13.6 x86_64

Error:

> Configure project :agl-processor
Evaluating project ':agl-processor' using build file '/Users/admin/Projects/programming/java/jet-brains/net.akehurst.language-3.5.0/net.akehurst.language/agl-processor/build.gradle.kts'.
Could not execute [class org.jetbrains.kotlin.gradle.plugin.statistics.DefaultKotlinBuildStatsService.buildFinished]

**Comment by dhakehurst** [comment]
try latest version

**Comment by dhakehurst** [comment]
does using the latest version solve your build issue ?

**Comment by dhakehurst** [comment]
Closed due to inactivity, assume fixed
