### ISSUE TITLE
Provide a threshold for searching possible matches

### ISSUE THREAD

**Issue by annekekleppe** [dhakehurst/net.akehurst.language#36]
Could you provide a manner to stop the parser after a certain number of possible trees has been found or after a certain depth of searches? Our use case is that we generate a grammar from user input, therefore we cannot guarantee that that parser will function correctly. We'd like to be able to stop the parsing and provide an error message in that case.

**Comment by dhakehurst** [comment]
good idea,
I will think about it.

**Comment by dhakehurst** [comment]
done
